### ISSUE TITLE
Bourns trimpot feet

### ISSUE THREAD

**Issue by wraybowling** [dhaillant/kicad-3dmodels#2]
The feet of bourns trim pots are always on the bottom. I've not inspected all the 3D files yet, but the PNG shows feet pointing in directions other than towards the PCB. Let's either update the all the files or the image.

**Comment by dhaillant** [comment]
According to https://www.bourns.com/pdfs/3296.pdf they have feet on both sides, no matter how the pots are oriented.

**Comment by wraybowling** [comment]
![image](https://user-images.githubusercontent.com/1120619/139270691-6f02c4b8-3c1a-453d-8aa1-e895e0e9c9bf.png)
I stand corrected!
